INSERT IGNORE INTO `products` (`categoryID`, `imgURL`, `productName`, `productDesc`) VALUES
(11, 'images/Candels/PillarChimney.png', 'Pillar Chimney Candle Shade', '3 sizes - 16\”, 18\” & 20\” x 4 W'),
(11, 'images/Candels/PillarCandle.png', 'White Glass Pillar Candle holders', '3 sizes - 16\”, 18\” & 20\” x 4 W'),
(11, 'images/Candels/AthenaTaper.png', 'Gold Mercury Athena Taper Candle holders', '1.5\” H x 2.5\” W'),
(11, 'images/Candels/StandardPinkVotive.png', 'Standard Votive Pink Mercury Glass', '2.75\” H x 1 3/4\” W'),
(11, 'images/Candels/PinkBowl.png', 'Gypsy Bowl Votive Holder', '2\” H x 2\” W'),
(11, 'images/Candels/CandelabraCrystal.jpg', 'Candelabra', '3 sizes - 6.5\”, 8.5\” & 11.5\” x 4\” W'),
(11, 'images/Candels/CandelabraAntiqueWhite.jpg', 'Candelabra', '4 arms Small Crystal & Antique White'),
(11, 'images/Candels/SquareGlassTaperHolders.JPG', 'Square Glass Taper Candle Holder', '2.5\" H x 1.5\" W'),
(11, 'images/Candels/SquareGlassTaperHoldersLarger.JPG', 'Square Glass Taper Candle Holder', '3\" H x 1.5\" W'),
(11, 'images/Candels/GradeHurricaneVotiveHolder.jpg', 'Grande Hurricane Votive Holder', 'Frosted White | 3.5\" H x 3\" W'),
(11, 'images/Candels/WhiteGlassPillarHolders.JPG', 'White Glass Pillar Holders', '3 sizes - 6.5\"H, 8.5\" H, 11.5\" H x 4\" W'),
(11, 'images/Candels/VotiveGoldStripe.jpg', 'Votive Gold Stripe Tea Light', 'Gold Stripe 4 1/4\" H x 2 1/2\" W'),
(11, 'images/Candels/PinkRosesVotive.jpg', 'Votive Tea Light', 'Pink Roses 3 1/4\" H x 2 1/2\" W'),
(11, 'images/Candels/PinchedGoldMercuryVotive.jpg', 'Votive Tea Light', 'Pinched Gold Mercury - 3\" H x 2 3/4\" W'),
(11, 'images/Candels/FrostedSparkleVotive.jpg', 'Votive Tea Light', 'Frosted Sparkle - 2 3/4\" H x 2 1/4\" W'),
(11, 'images/Candels/BlackLaceTealight.JPG', 'Votive Black Lace', '2.75\" H x 2.25\" W'),
(11, 'images/Candels/VotiveHoneycomb.png', 'Votive Honeycomb', '3\" H x 2 3/4\" W'),
(11, 'images/Candels/VotiveHobbnailBlue.png', 'Votive Hobnail Blue', '2.5\" H x 2.25\" W'),
(11, 'images/Candels/VotiveAquaRolyMercury.png', 'Votive Aqua Roly Mercury', '3.16\" H x 3.75\" W'),
(11, 'images/Candels/VotiveWindowMercury.png', 'Votive Aqua Window Mercury', '.5\" H x 3.25\" W'),
(11, 'images/Candels/GreenMercuryTealight.jpg', 'Votive Green Mercury', '3\" H x 2.8\" W'),
(11, 'images/Candels/GreenOasisTealight.JPG', 'Votive Green Oasis', '2.75\" H x 2.5\" W'),
(11, 'images/Candels/ChunkyVotiveHolder.jpg', 'Chunky Votive Holder', '2.5\" H x 2.5\" W'),
(11, 'images/Candels/CrystalVotiveHolder.jpg', 'Crystal Votive Holder', '2.5\" H x 2\" W'),
(11, 'images/Candels/DottieCandleholder.jpg', 'Dottie Votive Holder', '4.25\" H x 2.5\" W'),
(11, 'images/Candels/FrostedVotiveHolder.png', 'Frosted Sparkle Votive', '2.7\" H x 2.25\" W'),
(11, 'images/Candels/PrimroseMetallicGold.jpg', 'Primrose Metallic Gold', '3.25\" H x 2.5\" W'),
(11, 'images/Candels/PearlyMetallic.png', 'Pearly Metallic Gold', '4\" H x 3 1/4\" W'),
(11, 'images/Candels/ClassicMetallic.png', 'Classic Metallic Gold', '3.25\" H x 2.5\" W'),
(11, 'images/Candels/BohoMetallic.png', 'Boho Metallic Antique Gold Ombré', '4\" H x 2 3/4\" W'),
(11, 'images/Candels/CarrawayFluted.png', 'Carraway Fluted Edge', '2.5\" H x 3\" W'),
(11, 'images/Candels/RoyalMercury.png', 'Royal Mercury Gold', '4\" H x 2.75\" W'),
(11, 'images/Candels/Taper.jpg', 'Acrylic Taper Candlestick', '12\" H x 2.5\” W'),
(11, 'images/Candels/TealightCandleholderDecorativeWood.JPG', 'Decorative Wood Candle Holder', '3.25\" H x 3\" W'),
(11, 'images/Candels/RaisedDotPurple.jpg', 'Purple Glass Raised Dot Votive Holder', '3 5/8\” H x 3 1/8\” W'),
(11, 'images/Candels/PurpleHoneycombVotive.png', 'Purple Mercury Glass Honeycomb Votive Holder', '3\” H x 2.8\” W'),
(11, 'images/Candels/Winterwood.jpg', 'Winterwood Pillar Candle Holder', 'Varying Sizes approx. 6\" H x 5.5\" W');