INSERT IGNORE INTO `products` (`categoryID`, `imgURL`, `productName`, `productDesc`) VALUES
(5, 'images/Dishes/AntiqueRed.jpg', 'Garden Party', 'Dessert / Salad'),
(5, 'images/Dishes/Gold.JPG', 'Trestle Gold', 'Dessert / Salad'),
(5, 'images/Dishes/BluePlate.jpg', 'Trestle Aqua', 'Dessert / Salad'),
(5, 'images/Dishes/SaladSoupTrestleAqua.jpg', 'Trestle Aqua Bowl', 'Salad / Soup'),
(5, 'images/Dishes/Pineapple.jpg', 'British Colonial Pineapple', 'Dessert / Salad'),
(5, 'images/Dishes/BritishColonial.jpg', 'British Colonial Bamboo', 'Dessert / Salad'),
(5, 'images/Dishes/BritishColonialBowl.jpg', 'British Colonial Bowl', 'Soup'),
(5, 'images/Dishes/BlueBritishColonial.jpg', 'British Colonial Blue', 'Dessert / Salad'),
(5, 'images/Dishes/CasablanceWhiteGold.png', 'Casablanca White and Gold', 'Charger, Dinner, Salad, Bread & Butter'),
(5, 'images/Dishes/CasablancaBlackGold.jpg', 'Casablanca Black and Gold', 'Charger / Dinner / Salad'),
(5, 'images/Dishes/CasablancaSet.jpg', 'Casablanca Pink and Gold', 'Charger / Dinner / Salad / Bread & Butter'),
(5, 'images/Dishes/ClearCloud.jpg', 'Clear Hammered Cloud', 'Dinner / Salad'),
(5, 'images/Dishes/SlantedHammeredGlassBowl.jpg', 'Slanted Hammered Glass', 'Soup'),
(5, 'images/Dishes/PalmLeafDinnerwareDinnerbreadandbutteronly.jpg', 'Palm Leaf Dinnerware', 'Dinner Plate / Bread & Butter Plate'),
(5, 'images/Dishes/PeacockDinnerwaredinbreadonly.jpg', 'Peacock Dinnerware', 'Dinner Plate / Bread & Butter Plate'),
(5, 'images/Dishes/iridescentBowl.png', 'Iridescent Clear Bowl', 'Soup /  Salad'),
(5, 'images/Dishes/IridescentClear.jpg', 'Iridescent Clear Plate', 'Dinner & Salad Available');