INSERT IGNORE INTO `products` (`categoryID`, `imgURL`, `productName`, `productDesc`) VALUES
(3, 'images/glasses/IridescentStemlessWine18oz.jpg', 'Iridescent Stemless 18 oz.', 'Wine'),
(3, 'images/glasses/IridescentLoBallRocksWater.png', 'Iridescent', 'LoBall / Rocks / Water'),
(3, 'images/glasses/IridescentWine20_5oz.jpg', 'Iridescent 20.5 oz', 'Wine'),
(3, 'images/glasses/stemlessChampagneIridescent10_5oz.jpg', 'Iridescent Stemless 10.5 oz.', 'Champagne'),
(3, 'images/glasses/HiBallWaterTea14.5oz.jpg', 'HiBall 14.5 oz.', 'HiBall / Water / Tea'),
(3, 'images/glasses/MarquisbyWaterfordBradyLoBallRocksDoubleOldFashionedWater11oz.jpg', 'Marquis by Waterford Brady 11 oz.', 'LoBall / Rocks / Double Old Fashioned / Water'),
(3, 'images/glasses/MarquisbyWaterfordBradyWine12oz.jpg', 'Marquis by Waterford Brady 12 oz.', 'Wine'),
(3, 'images/glasses/MarquisbyWaterfordMarkhamWaterTeaDoubleOldFashionedHiBallSpecialtyDrink13oz.jpg', 'Marquis by Waterford Brady 13 oz.', ' Water / Tea / Double Old Fashioned / HiBall / Specialty Drink'),
(3, 'images/glasses/MarquisbyWaterfordWaterTeaDoubleOldFashionedHiBallSpecialtyDrink15oz.jpg', 'Marquis by Waterford 15 oz.', 'Water / Tea / Double Old Fashioned / HiBall / Specialty Drink'),
(3, 'images/glasses/MarquizByWaterfordMarkhamLoBallRocksDoubleOldFashionedWater11ozvertical.jpg', 'Marquis by Waterford LoBall 11 oz.', 'Markham / Rocks / Double Old Fashioned / Water'),
(3, 'images/glasses/MarquisbyWaterfordMarkham12ozWine.jpg', 'Marquis by Waterford LoBall 12 oz.', 'Markham / Wine'),
(3, 'images/glasses/MastersReserveContourWine12oz.png', 'Master\'s Reserve Contour 12 oz.', 'Wine'),
(3, 'images/glasses/MastersReserveLoBallRocksDoubleOldFashionedWater9oz.png', 'Master\'s Reserve LoBall 9 oz.', 'Rocks / Double Old Fashioned / Water'),
(3, 'images/glasses/MastersReservePrismWine13oz.png', 'Master\'s Reserve Prism 13 oz.', 'Wine'),
(3, 'images/glasses/PerfectPortionDessertTasterMartiniGlass2_5oz.png', 'Perfect Portion Dessert Taster 2.5 oz.', 'Mini Martini Glass'),
(3, 'images/glasses/PerfectPortionMartiniDessertGlass2_5oz.png', 'Martini Dessert Glass 2.5 oz.', 'Mini Dessert Glass'),
(3, 'images/glasses/SeriesVMartiniDessertGlass7_6oz.png', 'Series V Martin 7.6 oz.', 'Dessert Glass'),
(3, 'images/glasses/spiritDessertShotGlass1_75oz.png', 'Spirit Shot Glass 1.75 oz.', 'Shot / Dessert Glass'),
(3, 'images/glasses/Tulip9ozChampagne.jpg', 'Tulip 9 oz.', 'Champagne'),
(3, 'images/glasses/stolzle6_5oz.png', 'Stolzle 6.5 oz.', 'Wine / Champagne'),
(3, 'images/glasses/EmbassyRoyaleWaterTeaBeer16oz.jpg', 'Embassy Royale 16 oz.', 'Water / Tea / Beer'),
(3, 'images/glasses/EmbassyWaterBeerSangriaSpecialtyCocktail19_25oz.jpg', 'Embassy 19.25 oz.', 'Water / Beer / Sangria / Specialty Cocktail'),
(3, 'images/glasses/EmbassyFootedWaterTeaHiBall9oz.jpg', 'Embassy Footed 9 oz.', 'Water / Tea'),
(3, 'images/glasses/EmbassySmallWine6_5oz.jpg', 'Embassy Small 6.5 oz.', 'Wine'),
(3, 'images/glasses/AcopaLoBallRocksDoubleOldFashionedWater10oz.png', 'Acopa 10 oz.', 'LoBall / Rocks / Double Old Fashioned / Water'),
(3, 'images/glasses/catalina12ozMargarita.jpg', 'Catalina 12 oz.', 'Margarita'),
(3, 'images/glasses/Coffee8.5oz.png', 'Clear Cup 8.5 oz.', 'Coffee / Tea / Hot Chocolate'),
(3, 'images/glasses/godingerBlush7oz.jpg', 'Godinger Flute 7 oz.', 'Champagne'),
(3, 'images/glasses/godingerBlush9_5ozMargarita.jpg', 'Godinger 9.5 oz.', 'Margarita'),
(3, 'images/glasses/FitsnFloydAquaWaterWineSpecialityCocktail12oz.jpg', 'Fits & Floyd 12 oz.', 'Water / Wine / Specialty Cocktail');