INSERT IGNORE INTO `products` (`categoryID`, `imgURL`, `productName`, `productDesc`) VALUES
(6, 'images/silverware/GoldSilverware.png', 'Farrah Mercer Silverware', '5 Piece Place Setting (can be rented individually)'),
(6, 'images/silverware/WallaceBeeware.jpg', 'Wallace Beeware', '5 Piece Place Setting (can be rented individually)'),
(6, 'images/silverware/WallaceBeewareServingItems.jpg', 'Wallace Beeware', '5 Piece Place Setting (can be rented individually)'),
(6, 'images/silverware/WorldTableware5piecePlaceSetting.jpg', 'World Tableware', '5 Piece Place Setting (can be rented individually)'),
(6, 'images/catering/GoldDessertServers.jpg', 'Golden Servers', 'Servers'),
(8, 'images/napkins/ChampagneSatin.jpg', 'Champagne', 'Satin'),
(8, 'images/napkins/AntiqueGoldSatin.jpg', 'Antique Gold', 'Satin'),
(8, 'images/napkins/BrightGoldSatin.jpg', 'Bright Gold', 'Satin'),
(8, 'images/napkins/NavyBlueSatin.jpg', 'Navy Blue', 'Satin'),
(8, 'images/napkins/AppleRed.jpg', 'Apple Red', 'Polyester'),
(8, 'images/napkins/RedPolyester.jpg', 'Red', 'Polyester'),
(8, 'images/napkins/AquaBluePolyester.jpg', 'Aqua Blue', 'Polyester'),
(8, 'images/napkins/BabyBluePolyester.jpg', 'Baby Blue', 'Polyester'),
(8, 'images/napkins/BlushRoseGoldPolyesterjpg.jpg', 'Blush Rose Gold', 'Polyester'),
(8, 'images/napkins/BlackPolyester.jpg', 'Black', 'Polyester'),
(8, 'images/napkins/ChartreuseGreenPolyester.jpg', 'Chartreuse Green', 'Polyester'),
(8, 'images/napkins/EmeraldGreenPolyester.jpg', 'Emerald Green', 'Polyester'),
(8, 'images/napkins/FuschiaPolyester.jpg', 'Fuschia', 'Polyester'),
(8, 'images/napkins/GoldPolyester.jpg', 'Gold', 'Polyester'),
(8, 'images/napkins/IvoryPolyester.jpg', 'Ivory', 'Polyester'),
(8, 'images/napkins/NavyBluePolyester.jpg', 'Navy Blue', 'Polyester'),
(8, 'images/napkins/NudePolyester.jpg', 'Nude', 'Polyester'),
(8, 'images/napkins/OffWhitePolyester.jpg', 'Off White', 'Polyester'),
(8, 'images/napkins/PastelPinkPolyester.jpg', 'Pastel Pink', 'Polyester'),
(8, 'images/napkins/PinkPolyester.jpg', 'Pink', 'Polyester'),
(8, 'images/napkins/PoolBluePolyester.jpg', 'Pool Blue', 'Polyester'),
(8, 'images/napkins/RoyalBluePolyester.jpg', 'Royal Blue', 'Polyester'),
(8, 'images/napkins/TurquoisePolyester.jpg', 'Turquoise', 'Polyester'),
(8, 'images/napkins/WhitePolyester.jpg', 'White', 'Polyester');