INSERT IGNORE INTO `products` (`categoryID`, `imgURL`, `productName`, `productDesc`) VALUES 
(7, 'images/tablecloths/MedallionJaquardSheerGold120Round.jpg', 'Medallion Jaquard Sheer Gold Specialty', '120\" Round'),
(7, 'images/tablecloths/PayetteSilver.jpg', 'Payette Silver', '120\" Round'),
(7, 'images/tablecloths/PayetteGold.jpg', 'Payette Gold', '120\" Round'),
(7, 'images/tablecloths/PayetteBlack.jpg', 'Payette Black', '120\" Round'),
(7, 'images/tablecloths/Burlap.jpg', 'Burlap Specialty', '120\" Round'),
(7, 'images/tablecloths/MelroseWhiteDamask.jpg', 'Melrose White Damask', '120\" Round'),
(7, 'images/tablecloths/PintuckBlushRound.jpg', 'Pintuck Blush', '120\" Round'),
(7, 'images/tablecloths/PintuckChampagneRound.jpg', 'Pintuck Champagne', '120\" Round'),
(7, 'images/tablecloths/PintuckGoldRound.jpg', 'Pintuck Gold', '120\" Round'),
(7, 'images/tablecloths/PintuckIvoryRound.jpg', 'Pintuck Ivory', '120\" Round'),
(7, 'images/tablecloths/PintuckBlackRound.jpg', 'Pintuck Black', '120\" Round'),
(7, 'images/tablecloths/SequinChampagneRound.jpg', 'Sequin Champagne', '120\" Round'),
(7, 'images/tablecloths/SequinBlackRound.jpg', 'Sequin Black', '120\" Round'),
(7, 'images/tablecloths/PolyesterAppleRedRound.jpg', 'Polyester Apple Red', '120\" Round'),
(7, 'images/tablecloths/PolyesterRedRound.jpg', 'Polyester Red', '120\" Round'),
(7, 'images/tablecloths/PolyesterGoldRound.jpg', 'Polyester Gold', '120\" Round'),
(7, 'images/tablecloths/PolyesterAppleGreenRound.jpg', 'Polyester Apple Green', '120\" Round'),
(7, 'images/tablecloths/PolyesterSageGreenRound.jpg', 'Polyester Sage Green', '120\" Round'),
(7, 'images/tablecloths/PolyesterWillowGreenRound.jpg', 'Polyester Willow Green', '120\" Round'),
(7, 'images/tablecloths/PolyesterEmeraldGreenRound.jpg', 'Polyester Emerald Green', '120\" Round'),
(7, 'images/tablecloths/PolyesterDustyBlueRound.jpg', 'Polyester Dusty Blue', '120\" Round'),
(7, 'images/tablecloths/PolyesterPoolBlueRound.jpg', 'Polyester Pool Blue', '120\" Round'),
(7, 'images/tablecloths/PolyesterAquaRound.jpg', 'Polyester Aqua Blue', '120\" Round'),
(7, 'images/tablecloths/PolyesterTurquoiseRound.jpg', 'Polyester Turquoise', '120\" Round'),
(7, 'images/tablecloths/PolyesterLightBlueRound.jpg', 'Polyester Light Blue', '120\" Round'),
(7, 'images/tablecloths/PolyesterRoyalBlueRound.jpg', 'Polyester Royal Blue', '120\" Round'),
(7, 'images/tablecloths/PolyesterNavyBlueRound.jpg', 'Polyester Navy Blue', '120\" Round'),
(7, 'images/tablecloths/PolyesterFuschiaRound.jpg', 'Polyester Fuschia', '120\" Round'),
(7, 'images/tablecloths/PolyesterPinkRound.jpg', 'Polyester Pink', '120\" Round'),
(7, 'images/tablecloths/PolyesterLightPinkRound.jpg', 'Polyester Light Pink', '120\" Round'),
(7, 'images/tablecloths/PolyesterNudeRound.jpg', 'Polyester Nude', '120\" Round'),
(7, 'images/tablecloths/PolyesterOffWhiteRound.jpg', 'Polyester Off White', '120\" Round'),
(7, 'images/tablecloths/PolyesterIvoryRound.jpg', 'Polyester Ivory', '120\" Round'),
(7, 'images/tablecloths/PolyesterWhiteRound.jpg', 'Polyester White', '120\" Round'),
(7, 'images/tablecloths/PolyesterGrayRound.jpg', 'Polyester Gray', '120\" Round'),
(7, 'images/tablecloths/PolyesterBlackRound.jpg', 'Polyester Black', '120\" Round'),
(7, 'images/tablecloths/SatinRoundNavyBlue.jpg', 'Satin Navy Blue', '120\" Round'),
(7, 'images/tablecloths/SatinDustyRoseRound.jpg', 'Satin Dusty Rose', '120\" Round'),
(7, 'images/tablecloths/SatinGoldRound.jpg', 'Satin Gold', '120\" Round'),
(7, 'images/tablecloths/SatinChampagneRound.jpg', 'Satin Champagne', '120\" Round'),
(7, 'images/tablecloths/SatinSilverRound.jpg', 'Satin Silver', '120\" Round'),
(7, 'images/tablecloths/SatinOffWhiteRound.jpg', 'Satin Off White', '120\" Round'),
(7, 'images/tablecloths/SatinWhiteRound.jpg', 'Satin White', '120\" Round'),
(7, 'images/tablecloths/SpandexShinyMetalicChampagne.jpg', 'Spandex Shiny Metallic Champagne', '36\" '),
(7, 'images/tablecloths/SpandexWhite.jpg', 'Spandex White', '36\" '),
(7, 'images/tablecloths/SpandexNavyBlue.jpg', 'Spandex Navy', '36\" '),
(7, 'images/tablecloths/SpandexRoyalBlue.jpg', 'Spandex Royal Blue', '36\" '),
(7, 'images/tablecloths/SpandexDustyBlue.jpg', 'Spandex Dusty Blue', '36\" '),
(7, 'images/tablecloths/RedSpandex.jpg', 'Spandex Red', '36\" '),
(7, 'images/tablecloths/SpandexLightPink.jpg', 'Spandex Pink', '36\" '),
(7, 'images/tablecloths/SpandexBlack.jpg', 'Spandex Black', '36\" ');